import knownGameRoutes from "@/data/known-game-routes.json";

/**
 * Compact route set for middleware — must NOT import @/data/games.
 * Generated by scripts/generate-games-indexes.mjs (run during build).
 */
const KNOWN_GAME_DETAIL_ROUTES = new Set(
  (knownGameRoutes as string[]).map((route) => route.toLowerCase()),
);

/** True when providerSlug/gameSlug is a real catalogue detail route. */
export function isKnownGameDetailRoute(
  providerSlug: string,
  gameSlug: string,
): boolean {
  return KNOWN_GAME_DETAIL_ROUTES.has(
    `${providerSlug}/${gameSlug}`.toLowerCase(),
  );
}
