import {
  Cake,
  Calendar,
  Crown,
  Gem,
  Gift,
  Headphones,
  Lock,
  MessageCircle,
  PartyPopper,
  Percent,
  Rocket,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  Target,
  Ticket,
  Trophy,
  Users,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { VipIconKey } from "@/data/vip-page-content";

export const vipIconMap: Record<VipIconKey, LucideIcon> = {
  crown: Crown,
  zap: Zap,
  gift: Gift,
  percent: Percent,
  wallet: Wallet,
  cake: Cake,
  calendar: Calendar,
  headphones: Headphones,
  sparkles: Sparkles,
  shield: ShieldCheck,
  users: Users,
  trophy: Trophy,
  ticket: Ticket,
  party: PartyPopper,
  lock: Lock,
  smartphone: Smartphone,
  star: Star,
  message: MessageCircle,
  gem: Gem,
  rocket: Rocket,
  target: Target,
};
