import {
  AlertTriangle,
  Apple,
  Battery,
  Bell,
  Check,
  Crown,
  Download,
  Gamepad2,
  Gauge,
  Headphones,
  Lock,
  Monitor,
  RefreshCw,
  Rocket,
  Server,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Star,
  Store,
  Users,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { DownloadIconKey } from "@/data/download-page-content";

export const downloadIconMap: Record<DownloadIconKey, LucideIcon> = {
  zap: Zap,
  wallet: Wallet,
  gamepad: Gamepad2,
  store: Store,
  headphones: Headphones,
  crown: Crown,
  shield: ShieldCheck,
  gauge: Gauge,
  smartphone: Smartphone,
  apple: Apple,
  monitor: Monitor,
  check: Check,
  lock: Lock,
  virus: ShieldAlert,
  server: Server,
  bell: Bell,
  rocket: Rocket,
  star: Star,
  download: Download,
  refresh: RefreshCw,
  alert: AlertTriangle,
  battery: Battery,
  wifi: Wifi,
  users: Users,
};
